# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lamskidoski
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1

functions:
  app:
    handler: dist/handler.handler
    events:
      - http:
          path: create-cv
          method: post
          cors: true

plugins:
  - serverless-offline
